language: go
install: true
sudo: required
go:
  - 1.9.x
before_script:
  - ulimit -a
  - ulimit -a -S
  - ulimit -a -H
script:
  - ulimit -n 65536
  - while true; do cat /proc/sys/fs/file-nr; sleep 0.5; done &
  - ./run.sh "${TARGET}"
env:
  matrix:
    - TARGET=gopkg.in/mgo.v2
    - TARGET=github.com/globalsign/mgo
services:
  - mongodb
